# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('boolean', models.BooleanField(default=True)),
                ('decimal', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('integer', models.IntegerField(default=0)),
                ('charfield', models.CharField(default='', max_length=26)),
                ('filefield', models.FileField(upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
